//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int Point_ID { get; set; }
        public int Task_ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DeadLineDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<bool> ExecutionStatus { get; set; }
        public Nullable<bool> TaskForToday { get; set; }
        public string Description { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
