//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Points
    {
        public int Point_Id { get; set; }
        public int Task_id { get; set; }
        public string PointName { get; set; }
        public Nullable<System.DateTime> DeadLineDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<bool> ExecutionStatus { get; set; }
        public Nullable<bool> TaskForToday { get; set; }
        public string Description { get; set; }
    
        public virtual Tasks Tasks { get; set; }
    }
}
